export default {
  products: [
    {
      _id: "1",
      name: "Commodore 128",
      category: "Personal Computer",
      image: "../images/commodore128.jpg",
      price: 500,
      brand: "Commodore",
      rating: 4.5,
      reviews: 10,
      inStock: 3,
    },
    {
      _id: "2",
      name: "Commodore 64",
      category: "Personal Computer",
      image: "../images/commodore64.jpg",
      price: 300,
      brand: "Commodore",
      rating: 4.5,
      reviews: 7,
      inStock: 0,
    },
    {
      _id: "3",
      name: "Gameboy",
      category: "Portable",
      image: "../images/gameboy.jpg",
      price: 100,
      brand: "Nintendo",
      rating: 4.5,
      reviews: 5,
      inStock: 7,
    },
    {
      _id: "4",
      name: "Game Gear",
      category: "Portable",
      image: "../images/gamegear.jpg",
      price: 120,
      brand: "Sega",
      rating: 4.5,
      reviews: 3,
      inStock: 8,
    },
  ],
};
